In [18]:
#numpy
#Array trong numpy gom cac phan tu co cung kieu gia tri, chi so khong am bat dau tu 0, so chieu goi la rank cua mang Numpy va shape cuar mang la mot tuple cac so nguyen dua ra kich thuoc cua mang theo moi chieu

import numpy as np

a = np.array([[1, 2, 3],[1,42,2],[7,2,1]]) # Tạo array 1 chiều
# for index, element in enumerate(a):
#     print('%d - %d' % (index + 1 ,element))
a

array([[ 1,  2,  3],
       [ 1, 42,  2],
       [ 7,  2,  1]])

In [16]:
print(type(a))

# shape của mảng là một tuple các số nguyên đưa ra kích thước của mảng theo mỗi chiều.
print(a.shape) # in ra so hang va cot 1 metrix (sohang, so cot)
print(a[0,0]) # truy xuat phan tu a[hang,cot]
print(a[1,1])

<class 'numpy.ndarray'>
(2, 3)
1
42


In [20]:
#Tao array voi gia tri mac dinh
c = np.zeros((2,2)) #tao ma tran 2x2 voi tat ca phan tu bang 0
print(c)

[[0. 0.]
 [0. 0.]]


In [21]:
#Tao array voi gia tri cac phan tu bang1
b = np.ones((2,2))
print(b)

[[1. 1.]
 [1. 1.]]


In [27]:
# tao array voi tat ca gia tri cho truoc
d = np.full((4,2), 9)
print(d)

[[9 9]
 [9 9]
 [9 9]
 [9 9]]


In [29]:
# tao ma tran don vi voi kich thuoc cho truoc
matrix = np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
# tao ma tran voi cac phan tu ran dom
matrix2 = np.random.random((2,3))
print(matrix2)

[[0.36707943 0.26274242 0.54970797]
 [0.82797286 0.49166089 0.46358178]]


In [38]:
# Array indexing => giong nhu list => numpy array co the slice => can chi ro chieu khi slice
a = np.array([[1,2,3],[2,3,4],[5,6,7],])
print(a)

[[1 2 3]
 [2 3 4]
 [5 6 7]]


In [44]:
#slice 2 hang dau tien va 2 cot dau tien
b = a[:,1:3]
print(b)

[[2 3]
 [3 4]
 [6 7]]


In [52]:
# Tinh toan voi ma tran trong numpy

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x - y)

[[-4. -4.]
 [-4. -4.]]


In [53]:
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]


In [56]:
print(np.multiply(x, y)) ##nhan element-wise khong phai nhan ma tran thong thuong

# chia elemet -wise
print(np.divide(x, y))

[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [55]:
#nhan 2 ma tran
print(np.dot(x,y))

[[19. 22.]
 [43. 50.]]
